calculator: calculator.o test_calculator.o
	c++ -std=c++11 calculator.o test_calculator.o -o calculator

calculator.o: calculator.cpp
	c++ -std=c++11 -c calculator.cpp

test_calculator.o: test_calculator.cpp
	c++ -std=c++11 -c test_calculator.cpp
